// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataBaseFirst.Models;

public partial class DepartmentEmployeesView
{
    public int EmployeeId { get; set; }

    public string EmployeeName { get; set; }

    public int DepartmentId { get; set; }

    public string DepartmentName { get; set; }
}