// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataBaseFirst.Models;

public partial class Employee
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int Age { get; set; }

    public string Description { get; set; }

    public decimal Salary { get; set; }

    public int? ManagerId { get; set; }

    public int DepartmentId { get; set; }

    public virtual Department Department { get; set; }

    public virtual ICollection<Department> Departments { get; set; } = new List<Department>();

    public virtual ICollection<Employee> InverseManager { get; set; } = new List<Employee>();

    public virtual Employee Manager { get; set; }
}