// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DataBaseFirst.Models.Configurations;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
#nullable disable

namespace DataBaseFirst.Models;

public partial class SessionContext : DbContext
{
    public SessionContext()
    {
    }

    public SessionContext(DbContextOptions<SessionContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Department> Departments { get; set; }

    public virtual DbSet<DepartmentEmployeesView> DepartmentEmployeesViews { get; set; }

    public virtual DbSet<Employee> Employees { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
     => optionsBuilder.UseSqlServer("Data Source=.;Initial Catalog=Session;Persist Security Info=True;User ID=sa;Password=P@ssw0rd; TrustServerCertificate= true");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfiguration(new Configurations.DepartmentConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.DepartmentEmployeesViewConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.EmployeeConfiguration());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
