// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DataBaseFirst.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace DataBaseFirst.Models.Configurations
{
    public partial class DepartmentEmployeesViewConfiguration : IEntityTypeConfiguration<DepartmentEmployeesView>
    {
        public void Configure(EntityTypeBuilder<DepartmentEmployeesView> entity)
        {
            entity
                .HasNoKey()
                .ToView("DepartmentEmployeesView");

            entity.Property(e => e.DepartmentName).IsRequired();
            entity.Property(e => e.EmployeeName).IsRequired();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<DepartmentEmployeesView> entity);
    }
}
